### ISSUE TITLE
.es => .es6?

### ISSUE THREAD

**Issue by yetone** [houkanshan/day-and-night#1]
`.es` 在 `GitHub` 被识别成 `Erlang` 了，在某些 IDE 下会被当做 `ActionScript`

**Comment by houkanshan** [comment]
es6 也不准确啊，那 es7 怎么办，写 es7，那将来 es8 怎么办? 我之前用的就是 es6 ，后悔了。`.esnext` 倒是可以考虑..

不过这就是个随便写的网页嘛..

**Comment by yetone** [comment]
嗯 `.esnext` 比较不错，现在厂里的 `static_ng` 用的是 `.es6` = =
看来过段时间得换成 `.esnext` 了

**Comment by houkanshan** [comment]
阅读也是 `.es6`

**Comment by yetone** [comment]
话说阅读前端不用 `static_ng`？自己搞的一套系统吗？

**Comment by houkanshan** [comment]
嗯，比较简单，做 `static_ng` 前就分开了

**Comment by yetone** [comment]
是线上打包只保留源文件还是像 `static_ng` 一样线下打包并把编译后的文件也放入 `VCS` 中？

**Comment by houkanshan** [comment]
VCS 里只有源文件
